# Site settings
title: WWW / Effective Programming
description: > # this means to ignore newlines until "baseurl:"
  Effective Programming Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.effectiveprogramming.com/" # the base hostname & protocol for your site
twitter_username: effprog
github_username:  EffectiveProgramming

# Build settings
markdown: kramdown

# User added
excludes: go.sh
